# Generated by Django 4.1.12 on 2024-01-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(max_length=50)),
                ('collection_name', models.CharField(max_length=50)),
                ('chunk_size', models.IntegerField(default=1000)),
                ('overlap', models.IntegerField(default=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.CharField(max_length=60)),
                ('pinecone_api_key', models.CharField(max_length=50)),
                ('pinecone_env', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='filemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('index_name', models.CharField(max_length=50)),
                ('collection_name', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=50)),
                ('size', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('uploaded_name', models.CharField(max_length=50)),
            ],
        ),
    ]
