# Generated by Django 4.2.7 on 2024-03-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_promptpermissionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='vectormodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
